// ------------------------------------------------------------
// SECTION 1: WHAT IS A CONSTRUCTOR?
// ------------------------------------------------------------
// Interview-ready definition:
// A constructor is a special member of a class that runs automatically
// when an object is created. Its main purpose is to initialize object state.
//
// Key points:
// 1) Constructor name must match class name.
// 2) Constructor has no return type (not even void).
// 3) Called automatically by Java at object creation time.

// ------------------------------------------------------------
// SECTION 2: PROBLEM WITHOUT CONSTRUCTOR
// ------------------------------------------------------------
class CarWithoutConstructor {
    String carName;
    int price;
}

class ProblemWithoutConstructorDemo {
    public static void main(String[] args) {
        // Object 1
        CarWithoutConstructor car1 = new CarWithoutConstructor();
        car1.carName = "F1";
        car1.price = 100;

        // Object 2
        CarWithoutConstructor car2 = new CarWithoutConstructor();
        car2.carName = "BMW";
        car2.price = 200;

        // If we create many objects, manual assignment repeats everywhere.
        // Problems:
        // - Repeated code
        // - Easy to forget initialization
        // - Lower readability
        // - Harder maintenance

        System.out.println(car1.carName + " : " + car1.price);
        System.out.println(car2.carName + " : " + car2.price);
    }
}

// ------------------------------------------------------------
// SECTION 3: SOLUTION USING CONSTRUCTOR
// ------------------------------------------------------------
class CarWithConstructor {
    String carName;
    int price;

    // Parameterized constructor initializes fields immediately.
    CarWithConstructor(String carName, int price) {
        this.carName = carName;
        this.price = price;
    }
}

class ConstructorSolutionDemo {
    public static void main(String[] args) {
        CarWithConstructor car1 = new CarWithConstructor("F1", 100);
        CarWithConstructor car2 = new CarWithConstructor("BMW", 200);

        System.out.println(car1.carName + " : " + car1.price);
        System.out.println(car2.carName + " : " + car2.price);

        // Cleaner than creating object then assigning fields manually.
    }
}

// ------------------------------------------------------------
// SECTION 4: CLEAN COMPARISON
// ------------------------------------------------------------
class CleanComparison {
    public static void main(String[] args) {
        // Without constructor style
        CarWithoutConstructor c1 = new CarWithoutConstructor();
        c1.carName = "BMW";
        c1.price = 200;

        // With constructor style
        CarWithConstructor c2 = new CarWithConstructor("BMW", 200);

        System.out.println("Without constructor -> " + c1.carName + " " + c1.price);
        System.out.println("With constructor    -> " + c2.carName + " " + c2.price);
    }
}

// ------------------------------------------------------------
// SECTION 5: TYPES OF CONSTRUCTORS
// ------------------------------------------------------------
class ConstructorTypes {
    int value;
    String label;

    // 1) No-arg constructor (user-defined)
    ConstructorTypes() {
        value = 0;
        label = "No-arg";
    }

    // 2) Parameterized constructor
    ConstructorTypes(int value, String label) {
        this.value = value;
        this.label = label;
    }

    void print() {
        System.out.println(label + " : " + value);
    }

    public static void main(String[] args) {
        ConstructorTypes a = new ConstructorTypes();
        ConstructorTypes b = new ConstructorTypes(99, "Parameterized");
        a.print();
        b.print();
    }
}

// Important note:
// Default constructor is generated by Java only if you do not write any
// constructor in the class. Once you write at least one constructor,
// Java will not auto-generate the default constructor.

// ------------------------------------------------------------
// SECTION 6: CONSTRUCTOR OVERLOADING
// ------------------------------------------------------------
class Student {
    int id;
    String name;
    double marks;

    Student() {
        this.id = 0;
        this.name = "Unknown";
        this.marks = 0.0;
    }

    Student(int id, String name) {
        this.id = id;
        this.name = name;
        this.marks = 0.0;
    }

    Student(int id, String name, double marks) {
        this.id = id;
        this.name = name;
        this.marks = marks;
    }

    void show() {
        System.out.println(id + " " + name + " " + marks);
    }
}

class ConstructorOverloadingDemo {
    public static void main(String[] args) {
        Student s1 = new Student();
        Student s2 = new Student(101, "Asha");
        Student s3 = new Student(102, "Rahul", 88.5);

        s1.show();
        s2.show();
        s3.show();
    }
}

// ------------------------------------------------------------
// SECTION 7: THE this KEYWORD (GOLDEN RULE)
// ------------------------------------------------------------
// this -> current object
//
// Main uses in interview:
// 1) Access current object fields
// 2) Call current class method
// 3) Call another constructor using this()
// 4) Pass current object as argument
// 5) Return current object

// ------------------------------------------------------------
// SECTION 8: this FOR FIELD VS PARAMETER NAME CONFLICT
// ------------------------------------------------------------
class CarThisField {
    String carName;

    CarThisField(String carName) {
        // Left side is instance variable, right side is parameter.
        this.carName = carName;
    }

    void display() {
        System.out.println(carName);
    }

    public static void main(String[] args) {
        CarThisField c = new CarThisField("Audi");
        c.display();
        // Output: Audi
    }
}

// ------------------------------------------------------------
// SECTION 9: this TO CALL CURRENT CLASS METHOD
// ------------------------------------------------------------
class CarThisMethod {
    void start() {
        System.out.println("Car Started");
    }

    void drive() {
        this.start();
        System.out.println("Car Driving");
    }

    public static void main(String[] args) {
        CarThisMethod c = new CarThisMethod();
        c.drive();
    }
}

// ------------------------------------------------------------
// SECTION 10: this() FOR CONSTRUCTOR CHAINING
// ------------------------------------------------------------
class CarThisConstructor {
    String name;
    int price;

    CarThisConstructor() {
        // Calls parameterized constructor first.
        this("BMW", 5000000);
    }

    CarThisConstructor(String name, int price) {
        this.name = name;
        this.price = price;
    }

    void show() {
        System.out.println(name + " " + price);
    }

    public static void main(String[] args) {
        CarThisConstructor c = new CarThisConstructor();
        c.show();
        // Output: BMW 5000000
    }
}

// ------------------------------------------------------------
// SECTION 11: this AS METHOD ARGUMENT
// ------------------------------------------------------------
class ThisAsArgument {
    void show(ThisAsArgument t) {
        if (t == this) {
            System.out.println("Same current object passed");
        }
    }

    void display() {
        show(this);
    }

    public static void main(String[] args) {
        ThisAsArgument obj = new ThisAsArgument();
        obj.display();
    }
}

// ------------------------------------------------------------
// SECTION 12: this AS RETURN VALUE (METHOD CHAINING IDEA)
// ------------------------------------------------------------
class ThisAsReturn {
    int count = 0;

    ThisAsReturn increment() {
        count++;
        return this;
    }

    void show() {
        System.out.println("count = " + count);
    }

    public static void main(String[] args) {
        ThisAsReturn t = new ThisAsReturn();
        t.increment().increment().increment().show();
        // Output: count = 3
    }
}

// ------------------------------------------------------------
// SECTION 13: QUIZ 1 (TRICK) - x = x
// ------------------------------------------------------------
class QuizOne {
    int x = 10;

    QuizOne(int x) {
        // Wrong assignment: parameter assigned to itself.
        x = x;
    }

    void display() {
        System.out.println(x);
    }

    public static void main(String[] args) {
        QuizOne t = new QuizOne(50);
        t.display();
        // Output: 10
        // Reason: instance variable x never changed.
    }
}

// Correct version for learning:
class QuizOneFixed {
    int x = 10;

    QuizOneFixed(int x) {
        this.x = x;
    }

    void display() {
        System.out.println(x);
    }
}

// ------------------------------------------------------------
// SECTION 14: QUIZ 2 - CHAINING ORDER
// ------------------------------------------------------------
class QuizTwo {
    QuizTwo() {
        System.out.println("Constructor A");
    }

    QuizTwo(int x) {
        this();
        System.out.println("Constructor B");
    }

    public static void main(String[] args) {
        QuizTwo d = new QuizTwo(5);
        // Output:
        // Constructor A
        // Constructor B
    }
}

// ------------------------------------------------------------
// SECTION 15: QUIZ 3 - TWO OBJECTS, TWO STATES
// ------------------------------------------------------------
class QuizThree {
    String name;

    QuizThree(String name) {
        this.name = name;
    }

    void show() {
        System.out.println(this.name);
    }

    public static void main(String[] args) {
        QuizThree c1 = new QuizThree("BMW");
        QuizThree c2 = new QuizThree("Audi");

        c1.show();
        c2.show();
        // Output:
        // BMW
        // Audi
    }
}

// ------------------------------------------------------------
// SECTION 16: QUESTION 1 - MULTI-LEVEL CHAINING
// ------------------------------------------------------------
class ChainQuestionOne {
    ChainQuestionOne() {
        System.out.println("A");
    }

    ChainQuestionOne(int x) {
        this();
        System.out.println("B");
    }

    ChainQuestionOne(int x, int y) {
        this(10);
        System.out.println("C");
    }

    public static void main(String[] args) {
        ChainQuestionOne d = new ChainQuestionOne(5, 10);
        // Output:
        // A
        // B
        // C
    }
}

// ------------------------------------------------------------
// SECTION 17: QUESTION 2 - DEFAULT CONSTRUCTOR CONFUSION
// ------------------------------------------------------------
class DefaultConfusion {
    DefaultConfusion(int x) {
        System.out.println("Parameterized Constructor");
    }

    // If you try: new DefaultConfusion();
    // compile-time error because no empty constructor exists.
}

class DefaultConfusionFixed {
    DefaultConfusionFixed() {
        System.out.println("Default Constructor");
    }

    DefaultConfusionFixed(int x) {
        System.out.println("Parameterized Constructor");
    }
}

// ------------------------------------------------------------
// SECTION 18: QUESTION 3 - TRICKY BUT IMPORTANT
// ------------------------------------------------------------
class TrickyQuestionThree {
    int x;

    TrickyQuestionThree() {
        this(10);
        System.out.println("Default Constructor");
    }

    TrickyQuestionThree(int x) {
        this.x = x;
        System.out.println("Parameterized Constructor");
    }

    void display() {
        System.out.println(x);
    }

    public static void main(String[] args) {
        TrickyQuestionThree d = new TrickyQuestionThree();
        d.display();

        // Output:
        // Parameterized Constructor
        // Default Constructor
        // 10
    }
}

// ------------------------------------------------------------
// SECTION 19: COMMON MISTAKES CHECKLIST
// ------------------------------------------------------------
// 1) Writing return type in constructor (wrong): void Car() {}
// 2) Constructor name not matching class name
// 3) Forgetting this when parameter and field names match
// 4) Using this() not as first statement in constructor
// 5) Assuming Java gives default constructor after you wrote one

// ------------------------------------------------------------
// SECTION 20: INTERVIEW ONE-LINERS
// ------------------------------------------------------------
// Q: What is a constructor?
// A: Special class member used to initialize objects, auto-called at creation.
//
// Q: Why use constructor?
// A: To ensure object starts in valid state and reduce repeated setup code.
//
// Q: When is this used?
// A: this refers to current object, especially for field/parameter conflict
//    and constructor chaining.
//
// Q: Difference between method and constructor?
// A: Constructor has class name, no return type, runs automatically.
//    Method has return type and is called explicitly.

// ------------------------------------------------------------
// SECTION 21: FINAL QUICK REVISION FLOW
// ------------------------------------------------------------
// 1) Object created -> constructor runs automatically.
// 2) Constructor sets initial field values.
// 3) Use parameterized constructor to avoid repetitive assignments.
// 4) Use this.field = parameter to resolve same-name conflict.
// 5) Use this() for constructor chaining.
// 6) Practice output prediction for interview confidence.
//
// End of chapter notes.
